
namespace RMPCLApp.Login_Form
{
    partial class frmRecoverPassword
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmRecoverPassword));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.groupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btnRecover = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtEmailID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.groupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btnSubmit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtAnswer = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtQuestion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.groupBox3 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btnChangePassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtConfirmNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.groupBox1.BorderRadius = 1;
            this.groupBox1.BorderThickness = 1;
            this.groupBox1.Controls.Add(this.btnRecover);
            this.groupBox1.Controls.Add(this.txtEmailID);
            this.groupBox1.Controls.Add(this.bunifuLabel1);
            this.groupBox1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.groupBox1.LabelIndent = 10;
            this.groupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.groupBox1.Location = new System.Drawing.Point(11, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(726, 75);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Recover Password";
            // 
            // btnRecover
            // 
            this.btnRecover.AllowAnimations = true;
            this.btnRecover.AllowMouseEffects = true;
            this.btnRecover.AllowToggling = false;
            this.btnRecover.AnimationSpeed = 200;
            this.btnRecover.AutoGenerateColors = false;
            this.btnRecover.AutoRoundBorders = true;
            this.btnRecover.AutoSizeLeftIcon = true;
            this.btnRecover.AutoSizeRightIcon = true;
            this.btnRecover.BackColor = System.Drawing.Color.Transparent;
            this.btnRecover.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnRecover.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRecover.BackgroundImage")));
            this.btnRecover.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecover.ButtonText = "Recover";
            this.btnRecover.ButtonTextMarginLeft = 0;
            this.btnRecover.ColorContrastOnClick = 45;
            this.btnRecover.ColorContrastOnHover = 45;
            this.btnRecover.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnRecover.CustomizableEdges = borderEdges1;
            this.btnRecover.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRecover.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecover.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecover.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecover.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRecover.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRecover.ForeColor = System.Drawing.Color.White;
            this.btnRecover.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRecover.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecover.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRecover.IconMarginLeft = 11;
            this.btnRecover.IconPadding = 10;
            this.btnRecover.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRecover.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecover.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRecover.IconSize = 25;
            this.btnRecover.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRecover.IdleBorderRadius = 30;
            this.btnRecover.IdleBorderThickness = 1;
            this.btnRecover.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnRecover.IdleIconLeftImage = null;
            this.btnRecover.IdleIconRightImage = null;
            this.btnRecover.IndicateFocus = false;
            this.btnRecover.Location = new System.Drawing.Point(558, 30);
            this.btnRecover.Name = "btnRecover";
            this.btnRecover.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecover.OnDisabledState.BorderRadius = 1;
            this.btnRecover.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecover.OnDisabledState.BorderThickness = 1;
            this.btnRecover.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecover.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecover.OnDisabledState.IconLeftImage = null;
            this.btnRecover.OnDisabledState.IconRightImage = null;
            this.btnRecover.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRecover.onHoverState.BorderRadius = 1;
            this.btnRecover.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecover.onHoverState.BorderThickness = 1;
            this.btnRecover.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRecover.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRecover.onHoverState.IconLeftImage = null;
            this.btnRecover.onHoverState.IconRightImage = null;
            this.btnRecover.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRecover.OnIdleState.BorderRadius = 1;
            this.btnRecover.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecover.OnIdleState.BorderThickness = 1;
            this.btnRecover.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRecover.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRecover.OnIdleState.IconLeftImage = null;
            this.btnRecover.OnIdleState.IconRightImage = null;
            this.btnRecover.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRecover.OnPressedState.BorderRadius = 1;
            this.btnRecover.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecover.OnPressedState.BorderThickness = 1;
            this.btnRecover.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRecover.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRecover.OnPressedState.IconLeftImage = null;
            this.btnRecover.OnPressedState.IconRightImage = null;
            this.btnRecover.Size = new System.Drawing.Size(131, 32);
            this.btnRecover.TabIndex = 2;
            this.btnRecover.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRecover.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRecover.TextMarginLeft = 0;
            this.btnRecover.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRecover.UseDefaultRadiusAndThickness = true;
            this.btnRecover.Click += new System.EventHandler(this.BtnRecover_Click);
            // 
            // txtEmailID
            // 
            this.txtEmailID.AcceptsReturn = false;
            this.txtEmailID.AcceptsTab = false;
            this.txtEmailID.AnimationSpeed = 200;
            this.txtEmailID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailID.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailID.BackgroundImage")));
            this.txtEmailID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmailID.BorderRadius = 1;
            this.txtEmailID.BorderThickness = 1;
            this.txtEmailID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmailID.DefaultText = "";
            this.txtEmailID.FillColor = System.Drawing.Color.White;
            this.txtEmailID.HideSelection = true;
            this.txtEmailID.IconLeft = null;
            this.txtEmailID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailID.IconPadding = 10;
            this.txtEmailID.IconRight = null;
            this.txtEmailID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailID.Lines = new string[0];
            this.txtEmailID.Location = new System.Drawing.Point(278, 26);
            this.txtEmailID.MaxLength = 32767;
            this.txtEmailID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailID.Modified = false;
            this.txtEmailID.Multiline = false;
            this.txtEmailID.Name = "txtEmailID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailID.OnIdleState = stateProperties4;
            this.txtEmailID.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailID.PasswordChar = '\0';
            this.txtEmailID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailID.PlaceholderText = "";
            this.txtEmailID.ReadOnly = false;
            this.txtEmailID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailID.SelectedText = "";
            this.txtEmailID.SelectionLength = 0;
            this.txtEmailID.SelectionStart = 0;
            this.txtEmailID.ShortcutsEnabled = true;
            this.txtEmailID.Size = new System.Drawing.Size(228, 32);
            this.txtEmailID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailID.TabIndex = 1;
            this.txtEmailID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmailID.TextMarginBottom = 0;
            this.txtEmailID.TextMarginLeft = 3;
            this.txtEmailID.TextMarginTop = 0;
            this.txtEmailID.TextPlaceholder = "";
            this.txtEmailID.UseSystemPasswordChar = false;
            this.txtEmailID.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(19, 38);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(100, 20);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Enter E-Mail ID";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // groupBox2
            // 
            this.groupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.groupBox2.BorderRadius = 1;
            this.groupBox2.BorderThickness = 1;
            this.groupBox2.Controls.Add(this.btnSubmit);
            this.groupBox2.Controls.Add(this.txtAnswer);
            this.groupBox2.Controls.Add(this.bunifuLabel3);
            this.groupBox2.Controls.Add(this.txtQuestion);
            this.groupBox2.Controls.Add(this.bunifuLabel2);
            this.groupBox2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.groupBox2.LabelIndent = 10;
            this.groupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.groupBox2.Location = new System.Drawing.Point(11, 101);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(726, 115);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Security Question and Answer";
            // 
            // btnSubmit
            // 
            this.btnSubmit.AllowAnimations = true;
            this.btnSubmit.AllowMouseEffects = true;
            this.btnSubmit.AllowToggling = false;
            this.btnSubmit.AnimationSpeed = 200;
            this.btnSubmit.AutoGenerateColors = false;
            this.btnSubmit.AutoRoundBorders = true;
            this.btnSubmit.AutoSizeLeftIcon = true;
            this.btnSubmit.AutoSizeRightIcon = true;
            this.btnSubmit.BackColor = System.Drawing.Color.Transparent;
            this.btnSubmit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSubmit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSubmit.BackgroundImage")));
            this.btnSubmit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.ButtonText = "Submit";
            this.btnSubmit.ButtonTextMarginLeft = 0;
            this.btnSubmit.ColorContrastOnClick = 45;
            this.btnSubmit.ColorContrastOnHover = 45;
            this.btnSubmit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSubmit.CustomizableEdges = borderEdges2;
            this.btnSubmit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSubmit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubmit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubmit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubmit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSubmit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSubmit.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSubmit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSubmit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSubmit.IconMarginLeft = 11;
            this.btnSubmit.IconPadding = 10;
            this.btnSubmit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSubmit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSubmit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSubmit.IconSize = 25;
            this.btnSubmit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSubmit.IdleBorderRadius = 30;
            this.btnSubmit.IdleBorderThickness = 1;
            this.btnSubmit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSubmit.IdleIconLeftImage = null;
            this.btnSubmit.IdleIconRightImage = null;
            this.btnSubmit.IndicateFocus = false;
            this.btnSubmit.Location = new System.Drawing.Point(558, 69);
            this.btnSubmit.Name = "btnSubmit";
            this.btnSubmit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubmit.OnDisabledState.BorderRadius = 1;
            this.btnSubmit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnDisabledState.BorderThickness = 1;
            this.btnSubmit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubmit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubmit.OnDisabledState.IconLeftImage = null;
            this.btnSubmit.OnDisabledState.IconRightImage = null;
            this.btnSubmit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSubmit.onHoverState.BorderRadius = 1;
            this.btnSubmit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.onHoverState.BorderThickness = 1;
            this.btnSubmit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSubmit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.onHoverState.IconLeftImage = null;
            this.btnSubmit.onHoverState.IconRightImage = null;
            this.btnSubmit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSubmit.OnIdleState.BorderRadius = 1;
            this.btnSubmit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnIdleState.BorderThickness = 1;
            this.btnSubmit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSubmit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.OnIdleState.IconLeftImage = null;
            this.btnSubmit.OnIdleState.IconRightImage = null;
            this.btnSubmit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSubmit.OnPressedState.BorderRadius = 1;
            this.btnSubmit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubmit.OnPressedState.BorderThickness = 1;
            this.btnSubmit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSubmit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSubmit.OnPressedState.IconLeftImage = null;
            this.btnSubmit.OnPressedState.IconRightImage = null;
            this.btnSubmit.Size = new System.Drawing.Size(131, 32);
            this.btnSubmit.TabIndex = 4;
            this.btnSubmit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSubmit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSubmit.TextMarginLeft = 0;
            this.btnSubmit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSubmit.UseDefaultRadiusAndThickness = true;
            this.btnSubmit.Click += new System.EventHandler(this.BtnSubmit_Click);
            // 
            // txtAnswer
            // 
            this.txtAnswer.AcceptsReturn = false;
            this.txtAnswer.AcceptsTab = false;
            this.txtAnswer.AnimationSpeed = 200;
            this.txtAnswer.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAnswer.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAnswer.BackColor = System.Drawing.Color.Transparent;
            this.txtAnswer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAnswer.BackgroundImage")));
            this.txtAnswer.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAnswer.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAnswer.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAnswer.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAnswer.BorderRadius = 1;
            this.txtAnswer.BorderThickness = 1;
            this.txtAnswer.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAnswer.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAnswer.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAnswer.DefaultText = "";
            this.txtAnswer.FillColor = System.Drawing.Color.White;
            this.txtAnswer.HideSelection = true;
            this.txtAnswer.IconLeft = null;
            this.txtAnswer.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAnswer.IconPadding = 10;
            this.txtAnswer.IconRight = null;
            this.txtAnswer.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAnswer.Lines = new string[0];
            this.txtAnswer.Location = new System.Drawing.Point(278, 69);
            this.txtAnswer.MaxLength = 32767;
            this.txtAnswer.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAnswer.Modified = false;
            this.txtAnswer.Multiline = false;
            this.txtAnswer.Name = "txtAnswer";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAnswer.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAnswer.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAnswer.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAnswer.OnIdleState = stateProperties8;
            this.txtAnswer.Padding = new System.Windows.Forms.Padding(3);
            this.txtAnswer.PasswordChar = '\0';
            this.txtAnswer.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAnswer.PlaceholderText = "";
            this.txtAnswer.ReadOnly = false;
            this.txtAnswer.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAnswer.SelectedText = "";
            this.txtAnswer.SelectionLength = 0;
            this.txtAnswer.SelectionStart = 0;
            this.txtAnswer.ShortcutsEnabled = true;
            this.txtAnswer.Size = new System.Drawing.Size(228, 32);
            this.txtAnswer.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAnswer.TabIndex = 3;
            this.txtAnswer.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAnswer.TextMarginBottom = 0;
            this.txtAnswer.TextMarginLeft = 3;
            this.txtAnswer.TextMarginTop = 0;
            this.txtAnswer.TextPlaceholder = "";
            this.txtAnswer.UseSystemPasswordChar = false;
            this.txtAnswer.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(20, 69);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(48, 20);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Answer";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtQuestion
            // 
            this.txtQuestion.AcceptsReturn = false;
            this.txtQuestion.AcceptsTab = false;
            this.txtQuestion.AnimationSpeed = 200;
            this.txtQuestion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuestion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuestion.BackColor = System.Drawing.Color.Transparent;
            this.txtQuestion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuestion.BackgroundImage")));
            this.txtQuestion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtQuestion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQuestion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtQuestion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuestion.BorderRadius = 1;
            this.txtQuestion.BorderThickness = 1;
            this.txtQuestion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuestion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuestion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtQuestion.DefaultText = "";
            this.txtQuestion.FillColor = System.Drawing.Color.White;
            this.txtQuestion.HideSelection = true;
            this.txtQuestion.IconLeft = null;
            this.txtQuestion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuestion.IconPadding = 10;
            this.txtQuestion.IconRight = null;
            this.txtQuestion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuestion.Lines = new string[0];
            this.txtQuestion.Location = new System.Drawing.Point(278, 26);
            this.txtQuestion.MaxLength = 32767;
            this.txtQuestion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuestion.Modified = false;
            this.txtQuestion.Multiline = false;
            this.txtQuestion.Name = "txtQuestion";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuestion.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQuestion.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuestion.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuestion.OnIdleState = stateProperties12;
            this.txtQuestion.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuestion.PasswordChar = '\0';
            this.txtQuestion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuestion.PlaceholderText = "";
            this.txtQuestion.ReadOnly = false;
            this.txtQuestion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuestion.SelectedText = "";
            this.txtQuestion.SelectionLength = 0;
            this.txtQuestion.SelectionStart = 0;
            this.txtQuestion.ShortcutsEnabled = true;
            this.txtQuestion.Size = new System.Drawing.Size(228, 32);
            this.txtQuestion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQuestion.TabIndex = 1;
            this.txtQuestion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuestion.TextMarginBottom = 0;
            this.txtQuestion.TextMarginLeft = 3;
            this.txtQuestion.TextMarginTop = 0;
            this.txtQuestion.TextPlaceholder = "";
            this.txtQuestion.UseSystemPasswordChar = false;
            this.txtQuestion.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(19, 32);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(59, 20);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "Question";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // groupBox3
            // 
            this.groupBox3.BorderColor = System.Drawing.Color.LightGray;
            this.groupBox3.BorderRadius = 1;
            this.groupBox3.BorderThickness = 1;
            this.groupBox3.Controls.Add(this.btnChangePassword);
            this.groupBox3.Controls.Add(this.txtConfirmNewPassword);
            this.groupBox3.Controls.Add(this.txtNewPassword);
            this.groupBox3.Controls.Add(this.bunifuLabel5);
            this.groupBox3.Controls.Add(this.bunifuLabel4);
            this.groupBox3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.groupBox3.LabelIndent = 10;
            this.groupBox3.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.groupBox3.Location = new System.Drawing.Point(12, 229);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(725, 115);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Change Password";
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.AllowAnimations = true;
            this.btnChangePassword.AllowMouseEffects = true;
            this.btnChangePassword.AllowToggling = false;
            this.btnChangePassword.AnimationSpeed = 200;
            this.btnChangePassword.AutoGenerateColors = false;
            this.btnChangePassword.AutoRoundBorders = true;
            this.btnChangePassword.AutoSizeLeftIcon = true;
            this.btnChangePassword.AutoSizeRightIcon = true;
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.BackgroundImage")));
            this.btnChangePassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.ButtonText = "Change Password";
            this.btnChangePassword.ButtonTextMarginLeft = 0;
            this.btnChangePassword.ColorContrastOnClick = 45;
            this.btnChangePassword.ColorContrastOnHover = 45;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnChangePassword.CustomizableEdges = borderEdges3;
            this.btnChangePassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangePassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangePassword.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnChangePassword.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangePassword.IconMarginLeft = 11;
            this.btnChangePassword.IconPadding = 10;
            this.btnChangePassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangePassword.IconSize = 25;
            this.btnChangePassword.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.IdleBorderRadius = 30;
            this.btnChangePassword.IdleBorderThickness = 1;
            this.btnChangePassword.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.IdleIconLeftImage = null;
            this.btnChangePassword.IdleIconRightImage = null;
            this.btnChangePassword.IndicateFocus = false;
            this.btnChangePassword.Location = new System.Drawing.Point(558, 61);
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.OnDisabledState.BorderRadius = 1;
            this.btnChangePassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnDisabledState.BorderThickness = 1;
            this.btnChangePassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.OnDisabledState.IconLeftImage = null;
            this.btnChangePassword.OnDisabledState.IconRightImage = null;
            this.btnChangePassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.BorderRadius = 1;
            this.btnChangePassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.onHoverState.BorderThickness = 1;
            this.btnChangePassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.onHoverState.IconLeftImage = null;
            this.btnChangePassword.onHoverState.IconRightImage = null;
            this.btnChangePassword.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.OnIdleState.BorderRadius = 1;
            this.btnChangePassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnIdleState.BorderThickness = 1;
            this.btnChangePassword.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.IconLeftImage = null;
            this.btnChangePassword.OnIdleState.IconRightImage = null;
            this.btnChangePassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangePassword.OnPressedState.BorderRadius = 1;
            this.btnChangePassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnPressedState.BorderThickness = 1;
            this.btnChangePassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangePassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnPressedState.IconLeftImage = null;
            this.btnChangePassword.OnPressedState.IconRightImage = null;
            this.btnChangePassword.Size = new System.Drawing.Size(131, 32);
            this.btnChangePassword.TabIndex = 4;
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangePassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangePassword.TextMarginLeft = 0;
            this.btnChangePassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.UseDefaultRadiusAndThickness = true;
            this.btnChangePassword.Click += new System.EventHandler(this.BtnChangePassword_Click);
            // 
            // txtConfirmNewPassword
            // 
            this.txtConfirmNewPassword.AcceptsReturn = false;
            this.txtConfirmNewPassword.AcceptsTab = false;
            this.txtConfirmNewPassword.AnimationSpeed = 200;
            this.txtConfirmNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtConfirmNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtConfirmNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtConfirmNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtConfirmNewPassword.BackgroundImage")));
            this.txtConfirmNewPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtConfirmNewPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtConfirmNewPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtConfirmNewPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtConfirmNewPassword.BorderRadius = 1;
            this.txtConfirmNewPassword.BorderThickness = 1;
            this.txtConfirmNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtConfirmNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmNewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtConfirmNewPassword.DefaultText = "";
            this.txtConfirmNewPassword.FillColor = System.Drawing.Color.White;
            this.txtConfirmNewPassword.HideSelection = true;
            this.txtConfirmNewPassword.IconLeft = null;
            this.txtConfirmNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmNewPassword.IconPadding = 10;
            this.txtConfirmNewPassword.IconRight = null;
            this.txtConfirmNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmNewPassword.Lines = new string[0];
            this.txtConfirmNewPassword.Location = new System.Drawing.Point(278, 64);
            this.txtConfirmNewPassword.MaxLength = 32767;
            this.txtConfirmNewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtConfirmNewPassword.Modified = false;
            this.txtConfirmNewPassword.Multiline = false;
            this.txtConfirmNewPassword.Name = "txtConfirmNewPassword";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmNewPassword.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtConfirmNewPassword.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmNewPassword.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmNewPassword.OnIdleState = stateProperties16;
            this.txtConfirmNewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtConfirmNewPassword.PasswordChar = '\0';
            this.txtConfirmNewPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtConfirmNewPassword.PlaceholderText = "";
            this.txtConfirmNewPassword.ReadOnly = false;
            this.txtConfirmNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtConfirmNewPassword.SelectedText = "";
            this.txtConfirmNewPassword.SelectionLength = 0;
            this.txtConfirmNewPassword.SelectionStart = 0;
            this.txtConfirmNewPassword.ShortcutsEnabled = true;
            this.txtConfirmNewPassword.Size = new System.Drawing.Size(228, 32);
            this.txtConfirmNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtConfirmNewPassword.TabIndex = 3;
            this.txtConfirmNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtConfirmNewPassword.TextMarginBottom = 0;
            this.txtConfirmNewPassword.TextMarginLeft = 3;
            this.txtConfirmNewPassword.TextMarginTop = 0;
            this.txtConfirmNewPassword.TextPlaceholder = "";
            this.txtConfirmNewPassword.UseSystemPasswordChar = false;
            this.txtConfirmNewPassword.WordWrap = true;
            // 
            // txtNewPassword
            // 
            this.txtNewPassword.AcceptsReturn = false;
            this.txtNewPassword.AcceptsTab = false;
            this.txtNewPassword.AnimationSpeed = 200;
            this.txtNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPassword.BackgroundImage")));
            this.txtNewPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewPassword.BorderRadius = 1;
            this.txtNewPassword.BorderThickness = 1;
            this.txtNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNewPassword.DefaultText = "";
            this.txtNewPassword.FillColor = System.Drawing.Color.White;
            this.txtNewPassword.HideSelection = true;
            this.txtNewPassword.IconLeft = null;
            this.txtNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.IconPadding = 10;
            this.txtNewPassword.IconRight = null;
            this.txtNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.Lines = new string[0];
            this.txtNewPassword.Location = new System.Drawing.Point(278, 26);
            this.txtNewPassword.MaxLength = 32767;
            this.txtNewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewPassword.Modified = false;
            this.txtNewPassword.Multiline = false;
            this.txtNewPassword.Name = "txtNewPassword";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewPassword.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnIdleState = stateProperties20;
            this.txtNewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewPassword.PasswordChar = '\0';
            this.txtNewPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPassword.PlaceholderText = "";
            this.txtNewPassword.ReadOnly = false;
            this.txtNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPassword.SelectedText = "";
            this.txtNewPassword.SelectionLength = 0;
            this.txtNewPassword.SelectionStart = 0;
            this.txtNewPassword.ShortcutsEnabled = true;
            this.txtNewPassword.Size = new System.Drawing.Size(228, 32);
            this.txtNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPassword.TabIndex = 2;
            this.txtNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewPassword.TextMarginBottom = 0;
            this.txtNewPassword.TextMarginLeft = 3;
            this.txtNewPassword.TextMarginTop = 0;
            this.txtNewPassword.TextPlaceholder = "";
            this.txtNewPassword.UseSystemPasswordChar = false;
            this.txtNewPassword.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(19, 73);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(153, 20);
            this.bunifuLabel5.TabIndex = 1;
            this.bunifuLabel5.Text = "Confirm New Password";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(19, 35);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(96, 20);
            this.bunifuLabel4.TabIndex = 0;
            this.bunifuLabel4.Text = "New Password";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmRecoverPassword
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(754, 357);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.MaximizeBox = false;
            this.Name = "frmRecoverPassword";
            this.Text = "Recover Password";
            this.Load += new System.EventHandler(this.RecoverPassword_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRecover;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuGroupBox groupBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSubmit;
        private Bunifu.UI.WinForms.BunifuTextBox txtAnswer;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuestion;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuGroupBox groupBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangePassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtConfirmNewPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtNewPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
    }
}